# development:
#   jira_api_token: ATATT3xFfGF0PAbAt3Mkdyrs6TqvugnsrT1LIMZXL9oDG3A7A1w9G0DlsV0M69QfpDOAOp7demuKvy1o14r7Lemg16Y8sYNmUvt5WddLmd5mwrOj-TFdH05v1I8sCROpoH8GJYVfVpirHSF8U8qR7KMhwifzsFRL3PcQlyIDm_Elo1TnP285g-Q=6E185CB7

# production:
#   jira_api_token: ATATT3xFfGF0PAbAt3Mkdyrs6TqvugnsrT1LIMZXL9oDG3A7A1w9G0DlsV0M69QfpDOAOp7demuKvy1o14r7Lemg16Y8sYNmUvt5WddLmd5mwrOj-TFdH05v1I8sCROpoH8GJYVfVpirHSF8U8qR7KMhwifzsFRL3PcQlyIDm_Elo1TnP285g-Q=6E185CB7

# test:
#   jira_api_token: ATATT3xFfGF0PAbAt3Mkdyrs6TqvugnsrT1LIMZXL9oDG3A7A1w9G0DlsV0M69QfpDOAOp7demuKvy1o14r7Lemg16Y8sYNmUvt5WddLmd5mwrOj-TFdH05v1I8sCROpoH8GJYVfVpirHSF8U8qR7KMhwifzsFRL3PcQlyIDm_Elo1TnP285g-Q=6E185CB7
