ATLASSIAN_USERNAME="rkhairulislam@gmail.com"
ATLASSIAN_API_KEY="ATATT3xFfGF0PAbAt3Mkdyrs6TqvugnsrT1LIMZXL9oDG3A7A1w9G0DlsV0M69QfpDOAOp7demuKvy1o14r7Lemg16Y8sYNmUvt5WddLmd5mwrOj-TFdH05v1I8sCROpoH8GJYVfVpirHSF8U8qR7KMhwifzsFRL3PcQlyIDm_Elo1TnP285g-Q=6E185CB7"
PROJECT_KEY="CMA"
ISSUE_TYPE="Support"
JIRA_API_URL="https://collectionmanagementapp.atlassian.net"